name: deployment production

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
      
      - name: Setup pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Set up Node.js 👨🏻‍💻
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm' 
        
     
      - name: Install dependencies 👨🏻‍💻
        run: pnpm install --frozen-lockfile
        
      - name: Build app 🏗️
        run: pnpm build
        env:
          VITE_BASE_API: https://api.omniassisto.com/api/v1
          VITE_GOOGLE_MAPS_API_KEY: "${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}"
          VITE_FIREBASE_APIKEY: "${{ secrets.VITE_FIREBASE_APIKEY }}"
        
      
      - name: View dist folder contents 👀
        run: ls -l dist
      
      - name: SETUP SSH 💻
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh-keyscan -p ${{ secrets.HOST_PORT }} -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          
          cat <<EOF > ~/.ssh/config
          Host production_server
            HostName ${{ secrets.HOST }}
            User ${{ secrets.HOST_USER }}
            Port ${{ secrets.HOST_PORT }}
            IdentityFile ~/.ssh/id_rsa
            IdentitiesOnly yes
            PubkeyAcceptedAlgorithms +ssh-rsa
          EOF
          chmod 600 ~/.ssh/config

      
      - name: copy builds to server 🚀
        id: deploy
        run: |
          scp  -r dist/* production_server:/var/www/admin.omniassisto.com
          echo "** ¡Hola! Se ha realizado la conexión SSH correctamente. **"
        continue-on-error: false
      # ✅ Notificación de éxito global
      - name: Notify Success ✅
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ *OMNI ADMIN* || Despliegue exitoso en Production 🚀%0ARepo: ${{ github.repository }}%0ABranch: ${{ github.ref_name }}"
      # ⚠️ Notificación de fallo global
      - name: Notify Failure ❌
        if: failure()
        run: |
          LOG_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="❌ *OMNI ADMIN* || Falló el despliegue 🚨%0A🧱 Job: ${{ github.job }}%0A📦 Estado: ${{ job.status }}%0ARepo: ${{ github.repository }}%0ABranch: ${{ github.ref_name }}%0A🔍 [Ver logs en GitHub Actions]($LOG_URL)"
